// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGo0h-04fM3841aEf469hdvuwVV3oa39M',
    appId: '1:455122263704:web:addc6ecc66ae469b8b3aed',
    messagingSenderId: '455122263704',
    projectId: 'rettbase-campus',
    authDomain: 'rettbase-campus.firebaseapp.com',
    storageBucket: 'rettbase-campus.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE_3UD77_bgqRp4RY_oD30Qsae_aliDuA',
    appId: '1:455122263704:android:b778989fdc34c96a8b3aed',
    messagingSenderId: '455122263704',
    projectId: 'rettbase-campus',
    storageBucket: 'rettbase-campus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYMwgyJlj0JMNkPwfJNXSoIXPewVqKSHk',
    appId: '1:455122263704:ios:88089685dd5a92908b3aed',
    messagingSenderId: '455122263704',
    projectId: 'rettbase-campus',
    storageBucket: 'rettbase-campus.firebasestorage.app',
    iosBundleId: 'de.rettbase.campus.rettbaseCampus',
  );
}
